In [2]:
import cv2 
import numpy as np 
import matplotlib.pyplot as plt 

In [69]:

def GenerateCoordinate(shape):
    if shape == "circle":
        x = np.random.randint(60,340)
        y = np.random.randint(60,340)
    elif shape == "rect":
        x1 = np.random.randint(60,200)
        y1 = np.random.randint(3,250)

        x2 = np.random.randint(10,140)
        y2 = np.random.randint(10,140)

        x = (x1,y1);y=(x1+x2,y1+y2)
        
    elif shape == "square":
        pass 
    elif shape == "tri":
        pass 
    elif shape == "star":
        pass

    return x,y 

In [77]:
# generate Circle 

from turtle import color

shape = "rect"
image_cnt = 3

for cnt in range(image_cnt):
    plt.figure()
    img = np.zeros((512,512,3),dtype = np.uint8)
    coord_x,coord_y = GenerateCoordinate(shape)
    print(coord_x,coord_y)
    colour = np.random.randint(100,255,size=3)
    print(colour)
    if shape=="circle":
        radius = np.random.randint(50,100)
        # cv2.circle(img,(coord_x,coord_y),radius,(int(colour[0]),int(colour[1]),int(colour[-1])),thickness=-1)
    elif shape == "rect":
        cv2.rectangle(img,coord_x,coord_y,(int(colour[0]),int(colour[1]),int(colour[-1])),thickness=-1)

        plt.imshow(img)
        
    cv2.imwrite(f's-image-{cnt}.jpg',img)


    




(158, 216) (281, 254)
[146 131 160]
(153, 236) (199, 289)
[156 214 199]
(163, 6) (214, 40)
[176 196 215]


In [35]:

for cnt in range(110):
    img = np.zeros((512,512,3),dtype = np.uint8)
    colour = np.random.randint(100,255,size=3)
    p1= np.random.randint(70,250,size=2)
    p2 = p1[0],np.random.randint(150,250) + p1[0]
    p3 = p2[1],np.random.randint(150,250) + p2[0]
    # cv2.circle(img, p1, 2, (0,0,255), -1)
    # img = cv2.putText(img, f'{p1}', p1, cv2.FONT_HERSHEY_SIMPLEX, 1,(255, 0, 0),2, cv2.LINE_AA)
    # cv2.circle(img, p2, 2, (0,0,255), -1)
    # img = cv2.putText(img, f'{p2}', p2, cv2.FONT_HERSHEY_SIMPLEX, 1,(255, 0, 0),2, cv2.LINE_AA)
    # cv2.circle(img, p3, 2, (0,0,255
    # ), -1)
    # img = cv2.putText(img, f'{p3}', p3,cv2.FONT_HERSHEY_SIMPLEX, 1,(255, 0, 0),2, cv2.LINE_AA)
    pnts = np.array([p1,p2,p3])
    print(pnts)
    cv2.fillPoly(img,[pnts],(int(colour[0]),int(colour[1]),int(colour[-1])))
    # plt.imshow(img)
    cv2.imwrite(f"Triangle/t-image-{cnt}.jpg",img)

[[202  93]
 [202 438]
 [438 365]]
[[ 80 126]
 [ 80 257]
 [257 299]]
[[205 168]
 [205 358]
 [358 442]]
[[ 96 220]
 [ 96 274]
 [274 313]]
[[ 87 240]
 [ 87 249]
 [249 324]]
[[154 126]
 [154 321]
 [321 320]]
[[110 149]
 [110 349]
 [349 278]]
[[120 243]
 [120 305]
 [305 287]]
[[ 83 156]
 [ 83 271]
 [271 304]]
[[ 97  95]
 [ 97 327]
 [327 309]]
[[176 100]
 [176 415]
 [415 345]]
[[230 182]
 [230 391]
 [391 431]]
[[224 209]
 [224 440]
 [440 455]]
[[ 99 157]
 [ 99 262]
 [262 249]]
[[246 231]
 [246 444]
 [444 413]]
[[145 229]
 [145 324]
 [324 390]]
[[193 118]
 [193 361]
 [361 392]]
[[171 211]
 [171 403]
 [403 324]]
[[131  97]
 [131 293]
 [293 363]]
[[224 225]
 [224 407]
 [407 425]]
[[ 99 204]
 [ 99 339]
 [339 335]]
[[243 233]
 [243 487]
 [487 421]]
[[236 105]
 [236 416]
 [416 429]]
[[155 201]
 [155 318]
 [318 338]]
[[161 177]
 [161 392]
 [392 374]]
[[188  74]
 [188 358]
 [358 361]]
[[166 170]
 [166 367]
 [367 401]]
[[225 184]
 [225 423]
 [423 427]]
[[181 122]
 [181 332]
 [332 366]]
[[188 195]
 [1

/tmp/ipykernel_51642/1697736195.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  pentagram = np.array([[[[0, -1]] + [np.dot(m, (0, -1)) for m in rotations]]], dtype=np.float)
/tmp/ipykernel_51642/1697736195.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/r

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)